"""empty message

Revision ID: 0145dcb2ea22
Revises: 670f3245aa45
Create Date: 2023-07-30 17:20:09.055329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0145dcb2ea22"
down_revision = "670f3245aa45"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pceen", sa.Column("discontent", sa.Numeric(precision=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pceen", "discontent")
    # ### end Alembic commands ###
