"""added alcohol degree column for bar items

Revision ID: 01a8183de4df
Revises: 6272774aaf2b
Create Date: 2023-10-21 13:11:32.500598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "01a8183de4df"
down_revision = "6272774aaf2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bar_item", sa.Column("alcohol_degree", sa.Numeric(precision=4, scale=2), nullable=True))
    # ### end Alembic commands ###
    connection = op.get_bind()
    connection.execute("ALTER TABLE bar_daily_data ALTER COLUMN alcohol_bought_count TYPE NUMERIC(4, 2);")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bar_item", "alcohol_degree")
    # ### end Alembic commands ###
    connection = op.get_bind()
    connection.execute("ALTER TABLE bar_daily_data ALTER COLUMN alcohol_bought_count TYPE INTEGER;")
