""" Added Club Q permission

Revision ID: 05858c842f67
Revises: ce5aa8d2a2dc
Create Date: 2023-04-17 00:09:00.845693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05858c842f67'
down_revision = 'ce5aa8d2a2dc'
branch_labels = None
depends_on = None

old_options = ("photos", "pceen", "collection", "album", "role", "intrarez", "bar", "bar_stats")
new_options = sorted(old_options + ("club_q",))

old_type = sa.Enum(*old_options, name="permission_scope")
new_type = sa.Enum(*new_options, name="permission_scope")
tmp_type = sa.Enum(*new_options, name="_permission_scope")

def upgrade():
    # Create a temporary "_permission_scope" type, convert and drop the "old" type
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.execute("ALTER TABLE permission ALTER COLUMN scope TYPE _permission_scope USING scope::text::_permission_scope")
    old_type.drop(op.get_bind(), checkfirst=False)
    # Create and convert to the "new" scope type
    new_type.create(op.get_bind(), checkfirst=False)
    op.execute("ALTER TABLE permission ALTER COLUMN scope TYPE permission_scope USING scope::text::permission_scope")
    tmp_type.drop(op.get_bind(), checkfirst=False)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pceen", "sub_state")
    op.drop_table("subscription")
    op.drop_table("allocation")
    op.drop_table("rental")
    op.drop_table("payment")
    op.drop_table("device")
    op.drop_table("ban")
    op.drop_table("room")
    op.drop_table("bar")
    op.drop_table("offer")
    # ### end Alembic commands ###
    # Convert 'output_limit_exceeded' scope into 'timed_out'
    op.execute("DELETE FROM permission WHERE scope='club_q'")
    # Create a temporary "_permission_scope" type, convert and drop the "new" type
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.execute("ALTER TABLE permission ALTER COLUMN scope TYPE _permission_scope USING scope::text::_permission_scope")
    new_type.drop(op.get_bind(), checkfirst=False)
    # Create and convert to the "old" scope type
    old_type.create(op.get_bind(), checkfirst=False)
    op.execute("ALTER TABLE permission ALTER COLUMN scope TYPE permission_scope USING scope::text::permission_scope")
    tmp_type.drop(op.get_bind(), checkfirst=False)
