"""bekk

Revision ID: 128bfc39c690
Revises: 4f578e0fb6a0
Create Date: 2023-09-18 21:07:01.563912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '128bfc39c690'
down_revision = '4f578e0fb6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bekk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('promo', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('club_q_salle', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('club_q_salle', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('club_q_salle', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('club_q_salle', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_table('bekk')
    # ### end Alembic commands ###
