"""V4A tables

Revision ID: 14a7cb835d43
Revises: 01a8183de4df
Create Date: 2023-12-13 17:05:53.280596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a7cb835d43'
down_revision = '01a8183de4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v4a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('ticketing_open', sa.Boolean(), nullable=False),
    sa.Column('image_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('v4a_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('_v4a_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['_v4a_id'], ['v4a.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('v4a_representation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('_v4a_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['_v4a_id'], ['v4a.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('v4a_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('_representation_id', sa.Integer(), nullable=False),
    sa.Column('_pricing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['_pricing_id'], ['v4a_pricing.id'], ),
    sa.ForeignKeyConstraint(['_representation_id'], ['v4a_representation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('v4a_ticket')
    op.drop_table('v4a_representation')
    op.drop_table('v4a_pricing')
    op.drop_table('v4a')
    # ### end Alembic commands ###
