"""Change theatre image handliling

Revision ID: 221588dab96f
Revises: cc684694f9d4
Create Date: 2025-04-23 00:21:21.362149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221588dab96f'
down_revision = 'cc684694f9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saison', sa.Column('image_extension', sa.String(length=120), nullable=True))
    op.drop_column('saison', 'image_name')
    op.add_column('spectacle', sa.Column('image_extension', sa.String(length=120), nullable=True))
    op.drop_column('spectacle', 'image_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spectacle', sa.Column('image_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('spectacle', 'image_extension')
    op.add_column('saison', sa.Column('image_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('saison', 'image_extension')
    # ### end Alembic commands ###
