"""Bar (v2.2)

Revision ID: 34d63b2b9682
Revises: bc265a60afcf
Create Date: 2022-09-18 17:42:05.297987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "34d63b2b9682"
down_revision = "bc265a60afcf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bar_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("is_alcohol", sa.Boolean(), nullable=False),
        sa.Column("is_quantifiable", sa.Boolean(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "global_setting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bar_transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("_barman_id", sa.Integer(), nullable=False),
        sa.Column("_client_id", sa.Integer(), nullable=False),
        sa.Column("_item_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("balance_change", sa.Float(), nullable=False),
        sa.Column("is_reverted", sa.Boolean(), nullable=False),
        sa.Column("revert_date", sa.DateTime(), nullable=True),
        sa.Column("_reverter_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["_client_id"], ["pceen.id"]),
        sa.ForeignKeyConstraint(["_barman_id"], ["pceen.id"]),
        sa.ForeignKeyConstraint(["_reverter_id"], ["pceen.id"]),
        sa.ForeignKeyConstraint(["_item_id"], ["bar_item.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("pceen", sa.Column("bar_nickname", sa.String(length=128), nullable=True))
    op.add_column("pceen", sa.Column("bar_balance", sa.Float(), nullable=True))
    op.add_column("pceen", sa.Column("bar_deposit", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute("ALTER TYPE permission_scope ADD VALUE IF NOT EXISTS 'bar';")
    op.execute("ALTER TYPE permission_scope ADD VALUE IF NOT EXISTS 'bar_stats';")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pceen", "bar_deposit")
    op.drop_column("pceen", "bar_balance")
    op.drop_column("pceen", "bar_nickname")
    op.drop_table("bar_transaction")
    op.drop_table("global_setting")
    op.drop_table("bar_item")
    # ### end Alembic commands ###
