"""Remove Panier Bio module

Revision ID: 393b301f333e
Revises: 2da2af840d06
Create Date: 2026-08-07 03:46:48.669894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '393b301f333e'
down_revision = '2da2af840d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_panier_bio')
    op.drop_table('period_panier_bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    op.create_table('order_panier_bio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payment_made', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('treasurer_validate', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('taken', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('_period_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('_pceen_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['_pceen_id'], ['pceen.id'], name=op.f('order_panier_bio__pceen_id_fkey')),
    sa.ForeignKeyConstraint(['_period_id'], ['period_panier_bio.id'], name=op.f('order_panier_bio__period_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_panier_bio_pkey'))
    )
    op.create_table('period_panier_bio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('disabled_days', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('period_panier_bio_pkey'))
    )
    # ### end Alembic commands ###
