"""Permissions (v0.2)

Revision ID: 3a1b45e7c5bc
Revises: d3b595ecd1f2
Create Date: 2022-02-24 15:38:01.837415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1b45e7c5bc'
down_revision = 'd3b595ecd1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    permission_type = sa.Enum('all', 'read', 'write', 'delete',
                              name='permission_type')
    permission_scope = sa.Enum('pceen', 'photos', 'collection', 'album',
                               'role', name='permission_scope')
    op.create_table('permission',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', permission_type, nullable=False),
        sa.Column('scope', permission_scope, nullable=False),
        sa.Column('ref_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('index', sa.Integer(), nullable=False),
        sa.Column('color', sa.String(length=6), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_pceen_role_at',
        sa.Column('_pceen_id', sa.Integer(), nullable=False),
        sa.Column('_role_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['_pceen_id'], ['pceen.id'], ),
        sa.ForeignKeyConstraint(['_role_id'], ['role.id'], ),
        sa.PrimaryKeyConstraint('_pceen_id', '_role_id')
    )
    op.create_table('_role_permission_at',
        sa.Column('_role_id', sa.Integer(), nullable=False),
        sa.Column('_permission_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['_permission_id'], ['permission.id'], ),
        sa.ForeignKeyConstraint(['_role_id'], ['role.id'], ),
        sa.PrimaryKeyConstraint('_role_id', '_permission_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_role_permission_at')
    op.drop_table('_pceen_role_at')
    op.drop_table('role')
    op.drop_table('permission')
    # ### end Alembic commands ###
