"""Add payment type and bar settings

Revision ID: 4823493a9f27
Revises: af6bba14f130
Create Date: 2026-04-28 14:23:56.789231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4823493a9f27'
down_revision = 'af6bba14f130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the enum type first
    payment_type = postgresql.ENUM('internet', 'bar', name='paymenttype')
    payment_type.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('internet', 'bar', name='paymenttype'), nullable=False, server_default='internet'))

    # Custom data insertion
    global_setting = sa.table('global_setting',
        sa.column('name_fr', sa.String),
        sa.column('name_en', sa.String),
        sa.column('key', sa.String),
        sa.column('value', sa.Integer)
    )
    op.execute("DELETE FROM global_setting WHERE key IN ('BAR_RECHARGE_MIN', 'BAR_RECHARGE_MAX')") # Clean up if partially failed
    op.bulk_insert(global_setting, [
        {'name_fr': 'Rechargement bar min', 'name_en': 'Min bar recharge', 'key': 'BAR_RECHARGE_MIN', 'value': 30},
        {'name_fr': 'Rechargement bar max', 'name_en': 'Max bar recharge', 'key': 'BAR_RECHARGE_MAX', 'value': 10000},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('type')
    
    # Drop enum
    postgresql.ENUM('internet', 'bar', name='paymenttype').drop(op.get_bind(), checkfirst=True)
        
    op.execute("DELETE FROM global_setting WHERE key IN ('BAR_RECHARGE_MIN', 'BAR_RECHARGE_MAX')")
    # ### end Alembic commands ###
