"""make barman_id nullable

Revision ID: 4e0058cdde5a
Revises: 4823493a9f27
Create Date: 2026-04-29 17:37:20.599517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0058cdde5a'
down_revision = '4823493a9f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bar_transaction', schema=None) as batch_op:
        batch_op.alter_column('_barman_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bar_transaction', schema=None) as batch_op:
        batch_op.alter_column('_barman_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
