"""club_q_changes

Revision ID: 4f578e0fb6a0
Revises: 670f3245aa45
Create Date: 2023-09-10 10:12:12.948212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f578e0fb6a0'
down_revision = '670f3245aa45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pceen', sa.Column('discontent', sa.Numeric(precision=2, asdecimal=False), nullable=True))

    connection = op.get_bind()
    connection.execute("ALTER TABLE club_q_season ALTER COLUMN debut TYPE date;")
    connection.execute("ALTER TABLE club_q_season ALTER COLUMN fin TYPE date;")
    connection.execute("ALTER TABLE club_q_season ALTER COLUMN fin_inscription TYPE date;")
    connection.execute("ALTER TABLE club_q_salle ALTER COLUMN description TYPE varchar(2500);")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pceen', 'discontent')

    connection = op.get_bind()
    connection.execute("ALTER TABLE club_q_season ALTER COLUMN debut TYPE timestamp;")
    connection.execute("ALTER TABLE club_q_season ALTER COLUMN fin TYPE timestamp;")
    connection.execute("ALTER TABLE club_q_season ALTER COLUMN fin_inscription TYPE timestamp;")
    connection.execute("ALTER TABLE club_q_salle ALTER COLUMN description TYPE varchar(500);")
    # ### end Alembic commands ###
