"""empty message

Revision ID: 5a1908859504
Revises: 9998719f5679
Create Date: 2023-03-21 20:27:02.671192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a1908859504'
down_revision = '9998719f5679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_q_salle', sa.Column('lontitude', sa.Float(), nullable=True))
    op.drop_column('club_q_salle', 'longitude')
    op.drop_constraint('club_q_voeux__season_id_fkey', 'club_q_voeux', type_='foreignkey')
    op.drop_column('club_q_voeux', '_season_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_q_voeux', sa.Column('_season_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('club_q_voeux__season_id_fkey', 'club_q_voeux', 'club_q_season', ['_season_id'], ['id'])
    op.add_column('club_q_salle', sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('club_q_salle', 'lontitude')
    # ### end Alembic commands ###
