"""Club Q brochure

Revision ID: 6272774aaf2b
Revises: 128bfc39c690
Create Date: 2023-10-01 22:18:04.435541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6272774aaf2b'
down_revision = '128bfc39c690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_q_brochure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_season_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['_season_id'], ['club_q_season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_q_brochure')
    # ### end Alembic commands ###
