"""empty message

Revision ID: 65a43aa73c3c
Revises: ec764f0f21a4
Create Date: 2023-03-21 07:59:08.425583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a43aa73c3c'
down_revision = 'ec764f0f21a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_q_spectacle', sa.Column('_season_id', sa.Integer(), nullable=False))
    op.add_column('club_q_spectacle', sa.Column('_salle_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'club_q_spectacle', 'club_q_season', ['_season_id'], ['id'])
    op.create_foreign_key(None, 'club_q_spectacle', 'club_q_salle', ['_salle_id'], ['id'])
    op.add_column('club_q_voeux', sa.Column('_client_id', sa.Integer(), nullable=False))
    op.add_column('club_q_voeux', sa.Column('_spectacle_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'club_q_voeux', 'club_q_spectacle', ['_spectacle_id'], ['id'])
    op.create_foreign_key(None, 'club_q_voeux', 'club_q_client', ['_client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'club_q_voeux', type_='foreignkey')
    op.drop_constraint(None, 'club_q_voeux', type_='foreignkey')
    op.drop_column('club_q_voeux', '_spectacle_id')
    op.drop_column('club_q_voeux', '_client_id')
    op.drop_constraint(None, 'club_q_spectacle', type_='foreignkey')
    op.drop_constraint(None, 'club_q_spectacle', type_='foreignkey')
    op.drop_column('club_q_spectacle', '_salle_id')
    op.drop_column('club_q_spectacle', '_season_id')
    # ### end Alembic commands ###
