"""empty message

Revision ID: 6d743623fbc2
Revises: c3f509883fca
Create Date: 2023-03-21 20:14:26.807738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d743623fbc2'
down_revision = 'c3f509883fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('club_q_spectacle__season_id_fkey', 'club_q_spectacle', type_='foreignkey')
    op.drop_constraint('club_q_spectacle__salle_id_fkey', 'club_q_spectacle', type_='foreignkey')
    op.drop_column('club_q_spectacle', '_salle_id')
    op.drop_column('club_q_spectacle', '_season_id')
    op.drop_constraint('club_q_voeux__client_id_fkey', 'club_q_voeux', type_='foreignkey')
    op.drop_constraint('club_q_voeux__spectacle_id_fkey', 'club_q_voeux', type_='foreignkey')
    op.drop_constraint('club_q_voeux__season_id_fkey', 'club_q_voeux', type_='foreignkey')
    op.drop_column('club_q_voeux', '_spectacle_id')
    op.drop_column('club_q_voeux', '_season_id')
    op.drop_column('club_q_voeux', '_client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_q_voeux', sa.Column('_client_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('club_q_voeux', sa.Column('_season_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('club_q_voeux', sa.Column('_spectacle_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('club_q_voeux__season_id_fkey', 'club_q_voeux', 'club_q_season', ['_season_id'], ['id'])
    op.create_foreign_key('club_q_voeux__spectacle_id_fkey', 'club_q_voeux', 'club_q_spectacle', ['_spectacle_id'], ['id'])
    op.create_foreign_key('club_q_voeux__client_id_fkey', 'club_q_voeux', 'club_q_client', ['_client_id'], ['id'])
    op.add_column('club_q_spectacle', sa.Column('_season_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('club_q_spectacle', sa.Column('_salle_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('club_q_spectacle__salle_id_fkey', 'club_q_spectacle', 'club_q_salle', ['_salle_id'], ['id'])
    op.create_foreign_key('club_q_spectacle__season_id_fkey', 'club_q_spectacle', 'club_q_season', ['_season_id'], ['id'])
    # ### end Alembic commands ###
