"""empty message

Revision ID: 76aaff18d81b
Revises: 34d63b2b9682
Create Date: 2023-01-29 19:06:56.634735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76aaff18d81b'
down_revision = '34d63b2b9682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pceen', 'activated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pceen', 'activated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
