"""empty message

Revision ID: 8b89b68b04f7
Revises: 670f3245aa45
Create Date: 2023-08-05 19:42:24.780638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b89b68b04f7"
down_revision = "670f3245aa45"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pceen", sa.Column("discontent", sa.Numeric(precision=2, asdecimal=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pceen", "discontent")
    # ### end Alembic commands ###
