"""increase password hash length to 256

Revision ID: af6bba14f130
Revises: 170f7a7dced9
Create Date: 2026-04-25 21:02:41.749789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af6bba14f130'
down_revision = '170f7a7dced9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pceen', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.String(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pceen', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.String(length=256),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
