"""empty message

Revision ID: b7a5abdc05bc
Revises: 05858c842f67
Create Date: 2023-04-18 00:28:29.603360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a5abdc05bc'
down_revision = '05858c842f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_q_voeu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('places_demandees', sa.Integer(), nullable=False),
    sa.Column('priorite', sa.Integer(), nullable=False),
    sa.Column('places_minimum', sa.Integer(), nullable=True),
    sa.Column('places_attribuees', sa.Integer(), nullable=True),
    sa.Column('_pceen_id', sa.Integer(), nullable=False),
    sa.Column('_spectacle_id', sa.Integer(), nullable=False),
    sa.Column('_season_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['_pceen_id'], ['pceen.id'], ),
    sa.ForeignKeyConstraint(['_season_id'], ['club_q_season.id'], ),
    sa.ForeignKeyConstraint(['_spectacle_id'], ['club_q_spectacle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('club_q_voeux')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_q_voeux',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('places_demandees', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('priorite', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('places_minimum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('places_attribuees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('_spectacle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('_season_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['_client_id'], ['pceen.id'], name='club_q_voeux__client_id_fkey'),
    sa.ForeignKeyConstraint(['_season_id'], ['club_q_season.id'], name='club_q_voeux__season_id_fkey'),
    sa.ForeignKeyConstraint(['_spectacle_id'], ['club_q_spectacle.id'], name='club_q_voeux__spectacle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='club_q_voeux_pkey')
    )
    op.drop_table('club_q_voeu')
    # ### end Alembic commands ###
