"""SSO vip.espci.fr (v2.1)

Revision ID: bc265a60afcf
Revises: 3df8a0304608
Create Date: 2022-07-16 17:28:56.318583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "bc265a60afcf"
down_revision = "3df8a0304608"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pceen", sa.Column("espci_sso_enabled", sa.Boolean(), nullable=True))
    op.execute("UPDATE pceen SET espci_sso_enabled = false")
    op.alter_column("pceen", "espci_sso_enabled", type_=sa.Boolean(), nullable=False)
    op.alter_column("pceen", "_password_hash", nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE pceen SET _password_hash = '<no_password>' where _password_hash IS NULL")
    op.alter_column("pceen", "_password_hash", nullable=False)
    op.drop_column("pceen", "espci_sso_enabled")
    # ### end Alembic commands ###
