"""empty message

Revision ID: c378668b1992
Revises: f5ac807a4b95
Create Date: 2023-04-02 14:59:59.129736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c378668b1992'
down_revision = 'f5ac807a4b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_q_client')
    op.add_column('club_q_salle', sa.Column('nom', sa.String(length=64), nullable=False))
    op.add_column('club_q_salle', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('club_q_salle', sa.Column('url', sa.String(length=64), nullable=True))
    op.add_column('club_q_salle', sa.Column('adresse', sa.String(length=64), nullable=True))
    op.add_column('club_q_salle', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('club_q_salle', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('club_q_season', sa.Column('nom', sa.String(length=64), nullable=False))
    op.add_column('club_q_season', sa.Column('promo_orga', sa.Integer(), nullable=False))
    op.add_column('club_q_season', sa.Column('debut', sa.DateTime(), nullable=True))
    op.add_column('club_q_season', sa.Column('fin', sa.DateTime(), nullable=True))
    op.add_column('club_q_season', sa.Column('fin_inscription', sa.DateTime(), nullable=True))
    op.add_column('club_q_spectacle', sa.Column('nom', sa.String(length=64), nullable=False))
    op.add_column('club_q_spectacle', sa.Column('categorie', sa.String(length=64), nullable=True))
    op.add_column('club_q_spectacle', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('club_q_spectacle', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('club_q_spectacle', sa.Column('nb_tickets', sa.Integer(), nullable=False))
    op.add_column('club_q_spectacle', sa.Column('unit_price', sa.Float(), nullable=False))
    op.add_column('club_q_spectacle', sa.Column('_season_id', sa.Integer(), nullable=False))
    op.add_column('club_q_spectacle', sa.Column('_salle_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'club_q_spectacle', 'club_q_salle', ['_salle_id'], ['id'])
    op.create_foreign_key(None, 'club_q_spectacle', 'club_q_season', ['_season_id'], ['id'])
    op.add_column('club_q_voeux', sa.Column('places_demandees', sa.Integer(), nullable=False))
    op.add_column('club_q_voeux', sa.Column('priorite', sa.Integer(), nullable=False))
    op.add_column('club_q_voeux', sa.Column('places_minimum', sa.Integer(), nullable=True))
    op.add_column('club_q_voeux', sa.Column('places_attribuees', sa.Integer(), nullable=True))
    op.add_column('club_q_voeux', sa.Column('_client_id', sa.Integer(), nullable=False))
    op.add_column('club_q_voeux', sa.Column('_spectacle_id', sa.Integer(), nullable=False))
    op.add_column('club_q_voeux', sa.Column('_season_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'club_q_voeux', 'club_q_season', ['_season_id'], ['id'])
    op.create_foreign_key(None, 'club_q_voeux', 'pceen', ['_client_id'], ['id'])
    op.create_foreign_key(None, 'club_q_voeux', 'club_q_spectacle', ['_spectacle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'club_q_voeux', type_='foreignkey')
    op.drop_constraint(None, 'club_q_voeux', type_='foreignkey')
    op.drop_constraint(None, 'club_q_voeux', type_='foreignkey')
    op.drop_column('club_q_voeux', '_season_id')
    op.drop_column('club_q_voeux', '_spectacle_id')
    op.drop_column('club_q_voeux', '_client_id')
    op.drop_column('club_q_voeux', 'places_attribuees')
    op.drop_column('club_q_voeux', 'places_minimum')
    op.drop_column('club_q_voeux', 'priorite')
    op.drop_column('club_q_voeux', 'places_demandees')
    op.drop_constraint(None, 'club_q_spectacle', type_='foreignkey')
    op.drop_constraint(None, 'club_q_spectacle', type_='foreignkey')
    op.drop_column('club_q_spectacle', '_salle_id')
    op.drop_column('club_q_spectacle', '_season_id')
    op.drop_column('club_q_spectacle', 'unit_price')
    op.drop_column('club_q_spectacle', 'nb_tickets')
    op.drop_column('club_q_spectacle', 'date')
    op.drop_column('club_q_spectacle', 'description')
    op.drop_column('club_q_spectacle', 'categorie')
    op.drop_column('club_q_spectacle', 'nom')
    op.drop_column('club_q_season', 'fin_inscription')
    op.drop_column('club_q_season', 'fin')
    op.drop_column('club_q_season', 'debut')
    op.drop_column('club_q_season', 'promo_orga')
    op.drop_column('club_q_season', 'nom')
    op.drop_column('club_q_salle', 'longitude')
    op.drop_column('club_q_salle', 'latitude')
    op.drop_column('club_q_salle', 'adresse')
    op.drop_column('club_q_salle', 'url')
    op.drop_column('club_q_salle', 'description')
    op.drop_column('club_q_salle', 'nom')
    op.create_table('club_q_client',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ClubQClient_pkey')
    )
    # ### end Alembic commands ###
