"""empty message

Revision ID: c3f509883fca
Revises: 65a43aa73c3c
Create Date: 2023-03-21 20:12:13.416371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f509883fca'
down_revision = '65a43aa73c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_q_voeux', sa.Column('_season_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'club_q_voeux', 'club_q_season', ['_season_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'club_q_voeux', type_='foreignkey')
    op.drop_column('club_q_voeux', '_season_id')
    # ### end Alembic commands ###
