"""empty message

Revision ID: c40acbec57fe
Revises: 9dcb8c8cc89d
Create Date: 2023-01-29 19:22:02.866459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c40acbec57fe'
down_revision = '9dcb8c8cc89d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('representation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spectacle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('ticket_link', sa.String(length=120), nullable=True),
    sa.Column('director', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('image_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('theatre_spectacle')
    op.drop_table('theatre_representation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theatre_representation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='theatre_representation_pkey')
    )
    op.create_table('theatre_spectacle',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('ticket_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('director', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('image_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='theatre_spectacle_pkey')
    )
    op.drop_table('spectacle')
    op.drop_table('representation')
    # ### end Alembic commands ###
