"""v2_8_1

Revision ID: cd25f6f41bd7
Revises: 7f1be41e105f
Create Date: 2025-01-22 11:25:11.148034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd25f6f41bd7'
down_revision = '7f1be41e105f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_q_season', sa.Column('attributions_visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE club_q_season SET attributions_visible = TRUE")
    op.alter_column("club_q_season", "attributions_visible", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club_q_season', 'attributions_visible')
    # ### end Alembic commands ###
