"""empty message

Revision ID: ce5aa8d2a2dc
Revises: 8af1d33aa52f
Create Date: 2023-04-03 09:57:57.754414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5aa8d2a2dc'
down_revision = '8af1d33aa52f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_q_spectacle', sa.Column('image_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club_q_spectacle', 'image_name')
    # ### end Alembic commands ###
