"""Photos (v0.1)

Revision ID: d3b595ecd1f2
Revises: ec833dfdb4ae
Create Date: 2022-02-16 00:35:47.540654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b595ecd1f2'
down_revision = 'ec833dfdb4ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('visible', sa.Boolean(), nullable=False),
        sa.Column('dir_name', sa.String(length=120), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('description', sa.String(length=280), nullable=True),
        sa.Column('start', sa.Date(), nullable=True),
        sa.Column('end', sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('dir_name')
    )
    op.create_table('album',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('_collection_id', sa.Integer(), nullable=False),
        sa.Column('visible', sa.Boolean(), nullable=False),
        sa.Column('dir_name', sa.String(length=120), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('description', sa.String(length=280), nullable=True),
        sa.Column('start', sa.Date(), nullable=True),
        sa.Column('end', sa.Date(), nullable=True),
        sa.Column('featured', sa.Boolean(), nullable=False),
        sa.Column('nb_photos', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['_collection_id'], ['collection.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('_album_id', sa.Integer(), nullable=False),
        sa.Column('file_name', sa.String(length=120), nullable=False),
        sa.Column('width', sa.Integer(), nullable=False),
        sa.Column('height', sa.Integer(), nullable=False),
        sa.Column('_author_id', sa.Integer(), nullable=True),
        sa.Column('author_str', sa.String(length=64), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('lat', sa.Float(), nullable=True),
        sa.Column('lng', sa.Float(), nullable=True),
        sa.Column('caption', sa.String(length=280), nullable=True),
        sa.Column('featured', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['_album_id'], ['album.id'], ),
        sa.ForeignKeyConstraint(['_author_id'], ['pceen.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    op.drop_table('album')
    op.drop_table('collection')
    # ### end Alembic commands ###
