"""Add Casino module

Revision ID: d832bf54c113
Revises: 2da2af840d06
Create Date: 2026-07-13 18:44:23.807554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd832bf54c113'
down_revision = '393b301f333e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('open', 'locked', 'resolved', name='predictionstatus'), nullable=False),
    sa.Column('_author_id', sa.Integer(), nullable=False),
    sa.Column('_resolved_option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_author_id'], ['pceen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_prediction_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['_prediction_id'], ['prediction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('fk_prediction_resolved_option', 'prediction', 'prediction_option', ['_resolved_option_id'], ['id'])
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_pceen_id', sa.Integer(), nullable=False),
    sa.Column('_option_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['_option_id'], ['prediction_option.id'], ),
    sa.ForeignKeyConstraint(['_pceen_id'], ['pceen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


    with op.batch_alter_table('pceen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casino_coins', sa.Integer(), server_default='500', nullable=False))
        batch_op.add_column(sa.Column('last_casino_claim', sa.DateTime(), nullable=True))

    op.execute("ALTER TYPE permission_scope ADD VALUE 'casino'")
    op.execute("COMMIT")

    # Insert new permissions if they do not exist
    # 'read' permission for casino
    op.execute("INSERT INTO permission (type, scope) SELECT 'read', 'casino' WHERE NOT EXISTS (SELECT 1 FROM permission WHERE type = 'read' AND scope = 'casino' AND ref_id IS NULL)")
    # 'all' permission for casino
    op.execute("INSERT INTO permission (type, scope) SELECT 'all', 'casino' WHERE NOT EXISTS (SELECT 1 FROM permission WHERE type = 'all' AND scope = 'casino' AND ref_id IS NULL)")
    
    # Insert new Casino role
    op.execute("INSERT INTO role (name, index, color) SELECT 'Casino', 19, 'd4af37' WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'Casino')")
    
    # Associate 'all' permission with Casino role
    op.execute('''
        INSERT INTO _role_permission_at (_role_id, _permission_id)
        SELECT role.id, permission.id
        FROM role, permission
        WHERE role.name = 'Casino' AND permission.type = 'all' AND permission.scope = 'casino' AND permission.ref_id IS NULL
        AND NOT EXISTS (
            SELECT 1 FROM _role_permission_at 
            WHERE _role_id = role.id AND _permission_id = permission.id
        )
    ''')
    
    # Associate 'all' permission with Admin role
    op.execute('''
        INSERT INTO _role_permission_at (_role_id, _permission_id)
        SELECT role.id, permission.id
        FROM role, permission
        WHERE role.name = 'Admin' AND permission.type = 'all' AND permission.scope = 'casino' AND permission.ref_id IS NULL
        AND NOT EXISTS (
            SELECT 1 FROM _role_permission_at 
            WHERE _role_id = role.id AND _permission_id = permission.id
        )
    ''')

    # Associate 'read' permission with Élève role
    op.execute('''
        INSERT INTO _role_permission_at (_role_id, _permission_id)
        SELECT role.id, permission.id
        FROM role, permission
        WHERE role.name = 'Élève' AND permission.type = 'read' AND permission.scope = 'casino' AND permission.ref_id IS NULL
        AND NOT EXISTS (
            SELECT 1 FROM _role_permission_at 
            WHERE _role_id = role.id AND _permission_id = permission.id
        )
    ''')

    # ### end Alembic commands ###


def downgrade():
    # Remove role associations
    op.execute('''
        DELETE FROM _role_permission_at
        WHERE _permission_id IN (SELECT id FROM permission WHERE scope = 'casino')
    ''')
    
    # Remove role
    op.execute("DELETE FROM role WHERE name = 'Casino'")
    
    # Remove permissions
    op.execute("DELETE FROM permission WHERE scope = 'casino'")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.alter_column('scope',
               existing_type=sa.Enum('photos', 'intrarez', 'bar', 'bar_stats', 'club_q', 'bekk', 'theatre', 'panier_bio', 'calendar', 'casino', 'pceen', 'collection', 'album', 'role', 'club', name='permissionscope'),
               type_=postgresql.ENUM('album', 'bar', 'bar_stats', 'bekk', 'club_q', 'collection', 'intrarez', 'panier_bio', 'pceen', 'photos', 'role', 'theatre', 'club', 'calendar', name='permission_scope'),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.Enum('all', 'read', 'write', 'delete', name='permissiontype'),
               type_=postgresql.ENUM('all', 'read', 'write', 'delete', name='permission_type'),
               existing_nullable=False)

    with op.batch_alter_table('pceen', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('espci_email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('last_casino_claim')
        batch_op.drop_column('casino_coins')

    with op.batch_alter_table('club_q_salle', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=2500),
               existing_nullable=True)

    with op.batch_alter_table('bar_transaction', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('pay_item', 'top_up', name='bartransactiontype'),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('bar_daily_data', schema=None) as batch_op:
        batch_op.alter_column('alcohol_bought_count',
               existing_type=sa.Numeric(precision=4, scale=2, asdecimal=False),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.drop_table('bet')
    op.drop_table('prediction_option')
    op.drop_table('prediction')
    # ### end Alembic commands ###
