"""provlol

Revision ID: f83e2a07cdb1
Revises: 34d63b2b9682
Create Date: 2022-09-29 21:11:49.710612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f83e2a07cdb1"
down_revision = "34d63b2b9682"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bar_daily_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("_pceen_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("balance_change", sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=False),
        sa.Column("items_bought_count", sa.Integer(), nullable=False),
        sa.Column("alcohol_bought_count", sa.Integer(), nullable=False),
        sa.Column("total_spent", sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=False),
        sa.ForeignKeyConstraint(["_pceen_id"], ["pceen.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("_pceen_id", "date"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bar_daily_data")
    # ### end Alembic commands ###
